version: '3'

services:
  lagoon:
    build:
      context: ../../
      dockerfile: build/Dockerfile
    container_name: lagoon
    command: "./lagoon -d"
    volumes:
      - ../../lagoon.yml:/etc/lagoon/lagoon.yml:ro
      - data-volume:/var/lib/lagoon
    ports:
      - "9000:9000"
    logging:
      driver: fluentd
    depends_on:
      - elasticsearch
      - fluentbit

  nginx:
    image: nginx:1.21.1
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/lagoon.conf:ro
      - data-volume:/var/lib/lagoon

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  fluentbit:
    image: fluent/fluent-bit:1.6.5
    container_name: fluentbit
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:v2.29.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  data-volume:
